### PR TITLE
messaging: consistent messages for end of contract UX (SC-1562)

### PR DESCRIPTION
**Pull request by orndorffgrant**
## Why is this needed?

This improves the end-of-contract ux by doing the following:
- adds explanation to apt upgrade message that certain packages will fail to download and why and what to do
- changes generic "authentication failed" to clear error message on `pro enable`
- adds notice to status output (this is just for now until the bigger status rework happens)

## Test Steps
Run the new test, it requires being on the vpn

## Checklist

 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any integration tests accordingly
 - [ ] Changes here need to be documented, and this was done in: 

## Does this PR require extra reviews?

 - [ ] Yes
 - [x] No

### CODE REVIEW

**Comment by orndorffgrant** [comment]
>       * ⚠️ Please add a comment with justification of why messages are being altered.
>       * If the changes are trivial (e.g. a typo fix), then translations must be preserved.

Just a typo

**Comment by orndorffgrant** [comment]
CI fails unrelated

**Comment by orndorffgrant** [comment]
@renanrodrigo if you can run the test, please merge away says @lucasmoura 

@orndorffgrant add wsl fields to protest.example.yaml

**Comment by renanrodrigo** [comment]
@orndorffgrant can't merge, we have conflicts :D

**Review by lucasmoura — APPROVED** [review]

**Comment by lucasmoura** [comment]
@orndorffgrant Please merge it away once the conflicts are resolved

**Comment by orndorffgrant** [comment]
Updated - let's let CI run before merging

**Comment by orndorffgrant** [comment]
CI fails are unrelated

**Pull request merged**
