### PR TITLE
docs: Wall and fix broken link

### PR DESCRIPTION
**Pull request by aciba90**
no-jira no-lp no-gh

## Proposed Commit Message

```
docs: Wall and fix broken link

Treat Sphinx warnings as errors and add a GH check to verify the
docs are generated without errors.
```

## Test Steps

`tox -e docs`

## Checklist

 - [n/a] I have updated or added any unit tests accordingly
 - [n/a] I have updated or added any integration tests accordingly
 - [n/a] I have updated or added any documentation accordingly

## Does this PR require extra reviews?

 - [ ] Yes
 - [x] No

### CODE REVIEW

**Review by s-makin — APPROVED** [review]
Thanks :)

**Comment by aciba90** [comment]
Do you think it is worth adding GH check exercising `tox -e docs`, in order to catch doc errors/warnings?

**Comment by s-makin** [comment]
> Do you think it is worth adding GH check exercising `tox -e docs`, in order to catch doc errors/warnings?

I thought we already did, so if we don't, we probably should :) I'm in favour of that, but let's give the others a chance to add their thoughts

**Comment by aciba90** [comment]
As agreed, I added the GH check.

**Review by s-makin — APPROVED** [review]
LGTM :)

**Review by renanrodrigo — APPROVED** [review]

**Pull request merged**
