### PR TITLE
Ua reference docs update

### PR DESCRIPTION
**Pull request by dheyay**
## Why is this needed?

Updates the collect logs documentation. Changes `ua` reference to `pro`.
Fix for [#2849]

## Test Steps

No changes

## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] Changes here need to be documented, and this was done in: 

## Does this PR require extra reviews?

 - [ ] Yes
 - [x] No

### CODE REVIEW

**Review by lucasmoura — COMMENTED** [review]
Thanks for that @dheyay , but since this is tied to a feature that has not yet been released, we need to target the `docs-devel` branch instead.

We only push to the `docs` branch what we are ready to publish to the users.

**Comment by dheyay** [comment]
> Thanks for that @dheyay , but since this is tied to a feature that has not yet been released, we need to target the `docs-devel` branch instead.
> 
> We only push to the `docs` branch what we are ready to publish to the users.

Thanks for letting me know, updated accordingly!

**Comment by renanrodrigo** [comment]
@dheyay I think besides changing the target branch, you need to rebase your commit on top of it - otherwise you are bringing several more commits in this PR

**Comment by dheyay** [comment]
PR is being closed. Replaced by #2934.

**Pull request closed without merging**
