### PR TITLE
Bring reverted changes

### PR DESCRIPTION
**Pull request by lucasmoura**
Bring the "reverted" changes from release 29.4

### CODE REVIEW

**Comment by orndorffgrant** [comment]
Now this one needs to be fixed for the "priority" -> "permission" issue :)

**Comment by renanrodrigo** [comment]
REMINDER: we need to revert the reverts again for next release @renanrodrigo

**Comment by lucasmoura** [comment]
@orndorffgrant @renanrodrigo updated

**Review by orndorffgrant — APPROVED** [review]
CI fails are unrelated

**Review by renanrodrigo — APPROVED** [review]

**Pull request merged**
