### PR TITLE
cli: retry grabbing the lock

### PR DESCRIPTION
**Pull request by orndorffgrant**
## Why is this needed?

This helps when the timer job is running in the background and a cli command happens to collide with it. The timer job is usually over quickly, so retrying several times with a small sleep time should be sufficient.

## Test Steps

Everything should still work. Maybe try running more than one command at once and see one wait until the other is finished.

## Checklist

 - [x] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] Changes here need to be documented, and this was done in: 

## Does this PR require extra reviews?

 - [ ] Yes
 - [x] No

### CODE REVIEW

**Comment by orndorffgrant** [comment]
I could be convinced either way - the separation is kind of nice for readability IMO, and we may need the single attempt in the future? (or realize using the spinlock is actually a bad idea in some case?)
There are certainly some other things in there that could use refactoring though, like the use of methods on UAConfig

**Comment by lucasmoura** [comment]
I think it is fine if we remove it. We can remove it on a separate commit so that we can revert it easily in the future if we need the single attempt lock, specially because this module doesn't change that often

**Comment by orndorffgrant** [comment]
Sounds good, I'll add a commit on top of this one combining the lock classes

**Comment by orndorffgrant** [comment]
@renanrodrigo @lucasmoura updated!

**Review by renanrodrigo — APPROVED** [review]
lgtm thanks!

**Comment by renanrodrigo** [comment]
CI errors completely unrelated

**Pull request merged**
