### PR TITLE
Generate cli docs

### PR DESCRIPTION
**Pull request by renanrodrigo**
## Why is this needed?
This will generate documentation (RTD + manpage) based on the commands descriptions defined for the CLI.

`./tools/clidocgen.py manpage`
For the manpage, there is a template which is filled when the command is executed.

`./tools/clidocgen.py rst`
For the docs, it will generate the `commands.txt` file to be commited in the `docs` branch.

The docs PR including this output is #3286 

## Test Steps
Run the script, see what happens

---

- [x] *(un)check this to re-run the checklist action*

### CODE REVIEW

**Review by orndorffgrant — APPROVED** [review]
A nit, but looks great!

**Review by lucasmoura — APPROVED** [review]

**Comment by renanrodrigo** [comment]
Thanks for the approvals. I uploaded some small changes to the text (feel free to compare) because of the feecback on #3286

**Review by dheyay — APPROVED** [review]
Changes look great

**Comment by renanrodrigo** [comment]
One more quick iteration coming from #3286

**Pull request merged**
