### PR TITLE
Add arm64 tag to tests

### PR DESCRIPTION
**Pull request by dheyay**
## Why is this needed?

@arm64 tag added to basic tests for running weekly on new arm64 jenkins job

## Test Steps

---

- [x] *(un)check this to re-run the checklist action*

### CODE REVIEW

**Comment by dheyay** [comment]
Currently I have only added some tests as arm-64 tagged, also they are exclusively only `lxd-container` tests. the idea is to get these working and see how it goes, once these are working, we can expand to more tests and also vm tests.

**Review by renanrodrigo — APPROVED** [review]
@dheyay as we spoke before, I think we good to apply the changes but now you need some rebase - will merge as soon as done

**Review by renanrodrigo — CHANGES_REQUESTED** [review]
Seems you brought back some files from the dead
And there are merge conflicts in the diff

I would say it's valid to just start from scratch and re-tag your tests instead of trying to solve conflicts at this point

**Comment by dheyay** [comment]
@renanrodrigo I was working on that as soon as I realized this :sweat_smile:

**Comment by dheyay** [comment]
Closing PR, created a new one with no conflicts.

**Pull request closed without merging**
