### PR TITLE
Update messages for livepatch

### PR DESCRIPTION
**Pull request by dheyay**
Fixes: #3063

## Why is this needed?

This PR solves all of our problems because...

## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [x] I have updated or added any integration tests accordingly
 - [ ] Changes here need to be documented, and this was done in: 

## Does this PR require extra reviews?

 - [ ] Yes
 - [x] No

### CODE REVIEW

**Comment by dheyay** [comment]
> 🌎 This PR changes translatable messages. 🌏
> 
> Please select which scenarios apply. For further explanation, please read our [policy on message changes](https://github.com/canonical/ubuntu-pro-client/blob/docs/dev-docs/explanations/string_changes_policy.md).
> 
>     * [ ]  New messages are being added.
>       
>       * We will ask translators to take a look and add translations if they have time, but it will not block this PR.
> 
>     * [x]  Existing messages are being changed.
>       
>       * ⚠️ Please add a comment with justification of why messages are being altered.
>       * If the changes are trivial (e.g. a typo fix), then translations must be preserved.
>       * If the changes are substantial, then we will ask translators to take a look and update translations if they have time, but it will not block this PR.
> 
>     * [ ]  Existing messages are being deleted.
>       
>       * No special action needed.

Existing messages are updated to use the word "coverage" instead of "support" which currently implies a relation to other means of support e.g "phone support", etc.

**Review by orndorffgrant — COMMENTED** [review]
Thank you! Can you also update `LIVEPATCH_KERNEL_NOT_SUPPORTED_DESCRIPTION`, `LIVEPATCH_KERNEL_NOT_SUPPORTED_UNATTACHED`, `LIVEPATCH_LTS_REBOOT_REQUIRED`, and `REALTIME_LIVEPATCH_INCOMPATIBLE` for the same reason?

**Comment by dheyay** [comment]
Updated @orndorffgrant

**Comment by orndorffgrant** [comment]
Looks like the translations files need to be updated. Also, please keep the po file updates in a separate commit. Something like this should do it.
```
git reset HEAD~1
git add features uaclient/messages
git commit
./tools/update-pos.sh
git add debian/po
git commit -m "update-pos"
```

**Review by lucasmoura — APPROVED** [review]
Let's just wait for CI before merging it

**Review by orndorffgrant — APPROVED** [review]

**Pull request merged**
