### PR TITLE
Typo Fixes in docs

### PR DESCRIPTION
**Pull request by 106106**
no-jira no-lp no-gh
## Proposed Commit Message

```
summary: Minor typo fixes in docs

This is my first time contributing on GitHub to Canonical documentation. 
Please let me know if I am doing anything incorrectly or if there is something I can do to be a more effective contributor.

Thanks for your time reviewing this pull request!
```

## Checklist

 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any integration tests accordingly
 - [x] I have updated or added any documentation accordingly

## Does this PR require extra reviews?

 - [ ] Yes
 - [x] No

### CODE REVIEW

**Comment by orndorffgrant** [comment]
Hi @106106 thanks for contributing! Please let me know when you've [signed the CLA](https://ubuntu.com/legal/contributors/agreement) - I'll re-run the cla-check action and then we can merge after it passes.

**Comment by 106106** [comment]
Hi @orndorffgrant I've signed the CLA - Cheers!

**Comment by renanrodrigo** [comment]
Hello Jaimes,
The CLA check is done using your email, and as you are committing as `58838446+106106@users.noreply.github.com`, it can't find you.
I have manually checked Launchpad, and I see there you have it signed, and your github user is a member of `Canonical` so I GUESS you are yourself :D

**Comment by renanrodrigo** [comment]
(I see you have verified commits, but there is no GPG key in Launchpad so it keeps being just a guess)

**Comment by renanrodrigo** [comment]
So, @106106 , I'm merging this
keep in mind for future PRs (for any canonical repo, really) that it's highly recommended that you commit using your `@canonical.com` email - for a variety of reasons (:

**Review by renanrodrigo — APPROVED** [review]

**Comment by 106106** [comment]
@renanrodrigo Thanks! I'll keeping this in mind for future commits/pull requests. I really appreciate y'alls patience for my first GitHub pull request!

**Pull request merged**
