### PR TITLE
Update command output for pro fix dry-run

### PR DESCRIPTION
**Pull request by dheyay**
## Why is this needed?

This PR solves all of our problems because this updates the output for the CVE dry run to suggest the recommended way to attach a pro subscription.

Fixes: #3040 

## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] Changes here need to be documented, and this was done in: 

## Does this PR require extra reviews?

 - [ ] Yes
 - [ ] No

### CODE REVIEW

**Review by s-makin — APPROVED** [review]
LGTM, thanks! :)

**Review by orndorffgrant — APPROVED** [review]

**Review by orndorffgrant — CHANGES_REQUESTED** [review]
Sorry, approved before looking at CI.
This breaks at least one test. features/fix.feature:573

**Comment by dheyay** [comment]
@orndorffgrant updated, CI still red for integration tests on focal and xenial seem to be unrelated to the change made here.

**Comment by orndorffgrant** [comment]
@dheyay it is mostly self explanatory, but for the sake of adhering to processes, can you fill out and respond to https://github.com/canonical/ubuntu-pro-client/pull/3046#issuecomment-2045815811

**Comment by dheyay** [comment]
The existing messages for the command `pro fix --dry-run` are updated to show the recommended method of attaching to pro.

**Comment by dheyay** [comment]
> 🌎 This PR changes translatable messages. 🌏
> 
> Please select which scenarios apply. For further explanation, please read our [policy on message changes](https://github.com/canonical/ubuntu-pro-client/blob/docs/dev-docs/explanations/string_changes_policy.md).
> 
>     * [ ]  New messages are being added.
>       
>       * We will ask translators to take a look and add translations if they have time, but it will not block this PR.
> 
>     * [x]  Existing messages are being changed.
>       
>       * ⚠️ Please add a comment with justification of why messages are being altered.
>       * If the changes are trivial (e.g. a typo fix), then translations must be preserved.
>       * If the changes are substantial, then we will ask translators to take a look and update translations if they have time, but it will not block this PR.
> 
>     * [ ]  Existing messages are being deleted.
>       
>       * No special action needed.

The existing messages for the command `pro fix --dry-run` are updated to show the recommended method of attaching to pro.

**Review by orndorffgrant — APPROVED** [review]

**Pull request merged**
