### PR TITLE
auto-attach: make error message clearer

### PR DESCRIPTION
**Pull request by renanrodrigo**
## Why is this needed?
This PR solves all of our problems because now we tell people to run `auto-attach` after upgrades, and users are seeing the generic error.
When a machine tries to auto-attach and the contract server returns an error, print hints on what could have happened together with the error details.

## Test Steps
Integration test is good, can be tried in any cloud manually.

## Checklist
 - [ ] I have updated or added any unit tests accordingly
 - [x] I have updated or added any integration tests accordingly
 - [ ] Changes here need to be documented, and this was done in:

## Does this PR require extra reviews?
 - [ ] Yes
 - [x] No

### CODE REVIEW

**Comment by renanrodrigo** [comment]
> Please add a comment with justification of why messages are being altered

Updating the message is the whole point of this PR

> If the changes are substantial, then we will ask translators to take a look and update translations if they have time, but it will not block this PR.

No translation for this one yet anyway.

**Review by orndorffgrant — APPROVED** [review]
LGTM!

**Comment by renanrodrigo** [comment]
rebased and got rid of conflicts

**Comment by renanrodrigo** [comment]
re rebased and the maybe line is gone; merging

**Pull request merged**
