### PR TITLE
tests: Added lxd vm test for attach validtoken

### PR DESCRIPTION
**Pull request by dheyay**
## Why is this needed?

Adds an integration that attaches on a lxd-vm and asserts that esm-infra, esm-apps, and livepatch are all enabled by default.

## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [x] I have updated or added any integration tests accordingly
 - [ ] Changes here need to be documented, and this was done in: 

## Does this PR require extra reviews?

 - [ ] Yes
 - [ ] No

### CODE REVIEW

**Review by lucasmoura — COMMENTED** [review]
That's great @dheyay, but we already have a similar test to this one:
https://github.com/canonical/ubuntu-pro-client/blob/main/features/attached_enable.feature#L517

So I think it might be better improving this one instead

**Comment by orndorffgrant** [comment]
@lucasmoura @dheyay I missed that test when I recommended creating this new one, but I think some changes and a new test are still necessary.

Attaching and auto enabling esm-infra, esm-apps, and livepatch is the most widely used feature of pro-client, so I think it deserves its own test. The "Attached disable of livepatch" in attached_enable.feature only tests the auto-enablement as an aside while actually testing disabling livepatch.

Disabling livepatch does deserve a test, but shouldn't care too much about other services, so I think two things are warranted:
1. Create a new test in `attach_validtoken.feature` like this PR is currently doing. All it should do is attach and check that the expected services are auto-enabled. This should run on all LTS releases in a lxd-vm. This test doesn't need to do any `pro refresh` or extra `pro attach`.
2. Edit "Attached disable of livepatch" test to use --no-auto-enable when attaching. Then it doesn't need to assert that the esm services are enabled.

**Comment by lucasmoura** [comment]
@orndorffgrant I see the point here, but due to the cost of running VM tests, do you think it is worth to have a test that only checks the behavior of disabling livepatch ?

I still think the tests can be combined. Even though we are testing distinct features, they don't clash with each other and this would avoid spinning another VM for an extra test.

But let me know if you disagree

**Review by lucasmoura — APPROVED** [review]

**Review by orndorffgrant — APPROVED** [review]
Thank you! This just needs conflicts resolved since we merged the gherkin reformat

**Pull request merged**
