### PR TITLE
Bring release 30 to main

### PR DESCRIPTION
**Pull request by renanrodrigo**
This is bringing the release-30 only commits to main.

This is a bigger PR than usual because we did a great job fixing release 30 with granular and reviewable commits, and rounded it up to be great! But now it is harder to review this PR :D 

important things to notice:
- added integration tests still follow the old format for tags and filters - @orndorffgrant to add a commit organizing those
- all `update-pos` commits were ignoring when filtering this changeset, and a single run of the script is included after all commits. Let's see how that works out.

### CODE REVIEW

**Comment by orndorffgrant** [comment]
My commit on top is not fully tested yet

**Comment by orndorffgrant** [comment]
Just finished testing the behave-any commit - all modified tests are passing :rocket:

**Review by orndorffgrant — APPROVED** [review]
LGTM! Thanks for integrating this huge number of release fixes!

**Review by lucasmoura — APPROVED** [review]

**Comment by lucasmoura** [comment]
CI errors seem unrelated to the PR

**Pull request merged**
