### PR TITLE
config: pass cfg object to Livepatch

### PR DESCRIPTION
**Pull request by CalvoM**
In Livepatch UAConfig is called directly, when it should actually receive the current cfg as an argument.

## Why is this needed?
Solves some mocking issues when we have config files on our machines, i.e. user-config.json

## Test Steps

- Create the file `/var/lib/ubuntu-advantage/user-config.json` with the following content:
 ```
 {"metering_timer": "notanumber", "update_messaging_timer":-10}
 ```
- run `tox -e test`
## Checklist

 - [x] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] Changes here need to be documented, and this was done in: 

## Does this PR require extra reviews?

 - [ ] Yes
 - [x] No

### CODE REVIEW

**Comment by orndorffgrant** [comment]
If I understand the issue correctly, then I think the issue is in the function itself, not in the test. Would this diff fix it?

```diff
diff --git a/uaclient/config.py b/uaclient/config.py
index 7da064c4..05b5d667 100644
--- a/uaclient/config.py
+++ b/uaclient/config.py
@@ -562,7 +562,7 @@ class UAConfig:
         from uaclient.entitlements.entitlement_status import ApplicationStatus
         from uaclient.entitlements.livepatch import LivepatchEntitlement
 
-        livepatch_ent = LivepatchEntitlement()
+        livepatch_ent = LivepatchEntitlement(self)
         livepatch_status, _ = livepatch_ent.application_status()
 
         if livepatch_status == ApplicationStatus.ENABLED:
```

**Comment by CalvoM** [comment]
@orndorffgrant Yes, that fixes it.

**Comment by renanrodrigo** [comment]
@CalvoM would you please adapt the commit message to reflect the actual change?

**Comment by orndorffgrant** [comment]
One more nit: @CalvoM please remove "test: " from the beginning of the commit message

**Comment by CalvoM** [comment]
@orndorffgrant  Updated.

**Pull request merged**
