### PR TITLE
Update contributing docs

### PR DESCRIPTION
**Pull request by s-makin**
The contributing docs needed a bit of additional info on docs
contributions specifically.

## Please Squash this PR with this commit message
```
Updated the README in this branch to point people to the contributions
guide so they can find build instructions.

Split out "how to contribute to docs" from the style guide, then expanded
both with more detail.

Updated the docs index to point to the docs-branch version of
CONTRIBUTING.md
```
## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] Changes here need to be documented, and this was done in: 

## Does this PR require extra reviews?

 - [ ] Yes
 - [x] No

### CODE REVIEW

**Review by aciba90 — APPROVED** [review]
LGTM, thanks!

Not sure if this worth doing, as we do not have many external contributions. But, do you think it is worth referencing `dev-docs/documentation/contribute_docs.md` in https://github.com/canonical/ubuntu-pro-client/blob/main/.github/PULL_REQUEST_TEMPLATE.md? In that way we could drive external / newbie contributors to how to contribute to the docs.

**Comment by s-makin** [comment]
> LGTM, thanks!
> 
> Not sure if this worth doing, as we do not have many external contributions. But, do you think it is worth referencing `dev-docs/documentation/contribute_docs.md` in https://github.com/canonical/ubuntu-pro-client/blob/main/.github/PULL_REQUEST_TEMPLATE.md? In that way we could drive external / newbie contributors to how to contribute to the docs.

That's actually a really good idea, since we request docs be done before a feature can land. Good to point people to where they should look for that. I'll add it!

**Comment by aciba90** [comment]
For the record, the PR template has been removed because only the one from the `default` branch is used:  https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates

**Review by orndorffgrant — APPROVED** [review]
LGTM thank you!

**Pull request merged**
